# Generated by Django 2.1 on 2018-08-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
    ]
